AllCops:
  NewCops: enable

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/Lambda:
  EnforcedStyle: lambda

Style/SymbolArray:
  EnforcedStyle: brackets
